### ISSUE TITLE
Is this plugin still necessary?

### ISSUE THREAD

**Issue by wegry** [Macil/eslint-plugin-no-dupe-class-fields#11]
It seems ESLint might support this plugins functionality out of the box. As of writing, https://eslint.org/docs/rules/no-dupe-class-members seems to show that 

```javascript
class Foo {
  bar;
  bar() { }
}
```

as invalid. https://github.com/eslint/eslint/commit/b953a4ee12f120658a9ec27d1f8ca88dd3dfb599 seems to be where it was added.

**Comment by Macil** [comment]
Yeah, you're right that it's unnecessary now. I'm going to update the readme, and we should take it out of projects that use it.
